feat: updated pipeline to use new repo #179944
audaciaconsulting/Audacia.Locality pull request #15
Opened 2024-11-18 21:38 UTC by richardb355

### Version changed and CHANGELOG updated
- ❎ No version change required

### Code ready for review
- ✔ Code compiles, all tests pass, no debug/console statements or commented out code left in

### Unit tests added/updated
- ❎ No code changed

### README or other documentation updated
- ❎ Changes do not require documentation

### Added/updated logging
- ❎ No significant code changes

### Dependency licenses
- ❎ No new/upgraded dependencies

2024-11-19 12:33 UTC, jackpercy-acl requested changes

2024-11-19 13:15 UTC, richardb355 commented on build.yaml
> +schedules:
Removed

2024-11-19 13:23 UTC, jackpercy-acl submitted a review, later dismissed

2024-11-19 15:10 UTC, jackpercy-acl submitted a review, later dismissed

2024-11-21 08:46 UTC, jackpercy-acl approved these changes

2024-11-21 09:42 UTC, merged